site:
  name: 'The Matchmaking Bureau'
  site: 'https://matchmakingbureau.com'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: false

metadata:
  title:
    default: 'The Matchmaking Bureau | Private Matchmaking Southeast Asia'
    template: '%s | The Matchmaking Bureau'
  description: 'Private matchmaking across Southeast Asia for discerning professionals in the Philippines, Thailand, Indonesia, Malaysia, Singapore and Vietnam.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'The Matchmaking Bureau'
    images:
      - url: '~/assets/images/og-default-international.jpg'
        width: 1200
        height: 630
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false
        follow: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark:only'
